In [1]:
#import libraries
import numpy as np

In [39]:
def load_data_column(path,column_list=(0), has_header=True):
    """Load numeric CSV with missing values -> np.nan using only numpy.
    path: path to CSV file
    column_list: list of column indices to load (default: 0)
    has_header: whether the CSV file has a header row (default: True)
    """
    skip = 1 if has_header else 0
    data = np.genfromtxt(
        path,
        delimiter=",",
        skip_header=skip,
        usecols=(column_list),  # adjust based on relevant columns]       # force float to accommodate np.nan
        missing_values=0,       # treat empty strings as missing
        filling_values=0,   # replace missing with np.nan
        autostrip=True,
        invalid_raise=False
    )
    return data


In [24]:
def load_columns_name(path):
    """Load column names from CSV header."""
    with open(path, 'r') as f:
        header = f.readline().strip()
    return header.split(',')

In [36]:
#deprecated
def get_column_index(path, column_name):
    """Get the index of a column given its name."""
    columns = load_columns_name(path)
    try:
        return columns.index(column_name)
    except ValueError:
        raise ValueError(f"Column '{column_name}' not found in {path}")

In [58]:
def get_column_index_from_list(col_list,col_names):
    """Get the index of a column given its name from a list of column names.
    col_list: list of column names to find
    col_names: list of all column names
    """
    #check name for name, if not found print an error message with the name not found and continue adding the found columns
    for name in col_list:
        if name not in col_names:
            print(f"Column '{name}' not found in the provided list.")
        return [col_names.index(name) for name in col_list if name in col_names]

In [45]:
def expand_column(col,col_name):
    '''
    Expand a 1D column vector into a N array where N is the number of unique values in col.
    Each column in the output array is a binary indicator (0 or 1) of whether the corresponding
    entry in col matches the unique value for that column.
    col: 1D numpy array of categorical values
    '''
    unique_values = np.unique(col)
    print(f"Unique values in column '{col_name}': {unique_values}")
    expanded = np.zeros((col.size, unique_values.size), dtype=int)
    for i, val in enumerate(unique_values):
        expanded[:, i] = (col == val).astype(int)
    col_names = [f"{col_name}_{val}" for val in unique_values]
    return expanded, col_names

In [33]:
col=np.array([1,2,1,3,2,1,""])
expanded_col, col_names = expand_column(col, "category")
print(col)
print(expanded_col)
print(col_names)

['1' '2' '1' '3' '2' '1' '']
[[0 1 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]
['category_', 'category_1', 'category_2', 'category_3']


In [ ]:
#import data

x_test = load_data('../data/dataset/x_test.csv')
x_train = load_data('../data/dataset/x_train.csv')
y_train = load_data('../data/dataset/y_train.csv')

In [22]:
print(x_train)

[53. 33. 20. ... 39. 33. 32.]


In [25]:
x_col_name = load_columns_name('../data/dataset/x_test.csv')

In [26]:
print(x_col_name)

['Id', '_STATE', 'FMONTH', 'IDATE', 'IMONTH', 'IDAY', 'IYEAR', 'DISPCODE', 'SEQNO', '_PSU', 'CTELENUM', 'PVTRESD1', 'COLGHOUS', 'STATERES', 'CELLFON3', 'LADULT', 'NUMADULT', 'NUMMEN', 'NUMWOMEN', 'CTELNUM1', 'CELLFON2', 'CADULT', 'PVTRESD2', 'CCLGHOUS', 'CSTATE', 'LANDLINE', 'HHADULT', 'GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'HLTHPLN1', 'PERSDOC2', 'MEDCOST', 'CHECKUP1', 'BPHIGH4', 'BPMEDS', 'BLOODCHO', 'CHOLCHK', 'TOLDHI2', 'CVDSTRK3', 'ASTHMA3', 'ASTHNOW', 'CHCSCNCR', 'CHCOCNCR', 'CHCCOPD1', 'HAVARTH3', 'ADDEPEV2', 'CHCKIDNY', 'DIABETE3', 'DIABAGE2', 'SEX', 'MARITAL', 'EDUCA', 'RENTHOM1', 'NUMHHOL2', 'NUMPHON2', 'CPDEMO1', 'VETERAN3', 'EMPLOY1', 'CHILDREN', 'INCOME2', 'INTERNET', 'WEIGHT2', 'HEIGHT3', 'PREGNANT', 'QLACTLM2', 'USEEQUIP', 'BLIND', 'DECIDE', 'DIFFWALK', 'DIFFDRES', 'DIFFALON', 'SMOKE100', 'SMOKDAY2', 'STOPSMK2', 'LASTSMK2', 'USENOW3', 'ALCDAY5', 'AVEDRNK2', 'DRNK3GE5', 'MAXDRNKS', 'FRUITJU1', 'FRUIT1', 'FVBEANS', 'FVGREEN', 'FVORANG', 'VEGETAB1', 'EXERANY2', 'EXR

In [ ]:
col_list = ['_RFHLTH',
'_HCVU651', #Respondents aged 18-64 who have any form of health care coverage
'_RFHYPE5', #Adults who have been told they have high blood pressure by a doctor, nurse, or other health professional
'_CHOLCHK', #Cholesterol check within past five years
'_RFCHOL', #adults who have had their cholesterol checked and have been told by a doctor, nurse, or other health professional that it was high 59k nan
'_MICHD', #Respondents that have ever reported having coronary heart disease (CHD) or myocardial infarction (MI) 3k nan
'_ASTHMS1', #Computed asthma status
'_DRDXAR1', #Respondents who have had a doctor diagnose them as having some form of arthritis
'_PRACE1', #Preferred race category
'_MRACE1', #Calculated multiracial race categorization
'_HISPANC', #Hispanic, Latino/a, or Spanish origin calculated variable
'_RACE', #Race/ethnicity categories
'_RACEG21', #White non-Hispanic race group
'_RACEGR3', #Five-level race/ethnicity category
'_RACE_G1', #Race groups used for internet prevalence tables 7k nan
'_AGEG5YR', #Fourteen-level age category
'_AGE65YR', #Two-level age category
'_AGE80', #Imputed Age value collapsed above 80
'_AGE_G', #Six-level imputed age category
'HTIN4', #Reported height in inches #17k nan
'HTM4', #Reported height in meters 15k nan
'WTKG3', #Reported weight in kilograms
'BMI5', #Body Mass Index (BMI) 36k nan
'BMI5CAT', #Four-categories of Body Mass Index (BMI) 36k nan
'RFBMI5', #Adults who have a body mass index greater than 25.00 (Overweight or Obese) 36k nan
'CHLDCNT', #Number of children in household
'EDUCAG', #Level of education completed
'INCOMG', #Income categories
'SMOKER3', #Four-level smoker status: Everyday smoker, Someday smoker, Former smoker, Non-smoker
'RFSMOK3', #Adults who are current smokers
'DRNKANY5', #Adults who reported having had at least one drink of alcohol in the past 30 days.
'DROCDY3_', #Drink-occasions-per-day
'RFBING5', #Binge drinkers (males having five or more drinks on one occasion, females having four or more drinks on one occasion)
'DRNKWEK', #Calculated total number of alcoholic beverages consumed per week
'RFDRHV5', #Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per
'FTJUDA1_', #Fruit juice intake in times per day 38k nan
'FRUTDA1_', #Fruit intake in times per day 36k nan
'BEANDAY_', #Bean intake in times per day 39k nan
'GRENDAY_', #Dark green vegetable intake in times per day 38k nan
'ORNGDAY_', #Orange-colored vegetable intake in times per day 39k nan
'VEGEDA1_', #Other vegetable intake in times per day 41k nan
'_MISFRTN', #The number of missing fruit responses
'_MISVEGN', #The number of missing vegetable responses
'_FRTRESP', #Missing any fruit responses
'_VEGRES', #Missing any vegetable responses
'FRUTSUM', #Total fruits consumed per day 43k nan
'VEGESUM', #Total vegetables consumed per day 51k nan
'FRTLT1', #Consume Fruit 1 or more times per day
'VEGLT1', #Consume Vegetables 1 or more times per day
'FRT16', #Reported consuming Fruit >16 per day
'VEG23', #Reported consuming Vegetables >23 per day
'FRUITEX', #Fruit Exclusion from analyses
'VEGETEX', #Vegetable Exclusion from analyses
'TOTINDA', #Adults who reported doing physical activity or exercise during the past 30 days other than their regular job
'METVL11_', #Activity MET Value for First Activity 146k nan
'METVL21_', #Activity MET Value for Second Activity 151k nan
'MAXVO2_', #Estimated Age-Gender Specific Maximum Oxygen Consumption
'FC60_', #Estimated Functional Capacity
'ACTIN11_', #Estimated Activity Intensity for First Activity 150k nan
'ACTIN21_', #Estimated Activity Intensity for Second Activity 154k nan
'PADUR1_', #Estimated Duration in Minutes for First Activity 154k nan
'PADUR2_', #Minutes of Second Activity 249k nan
'PAFREQ1_', #Physical Activity Frequency per Week for First Activity 150k nan
'PAFREQ2_', #Physical Activity Frequency per Week for Second Activity 246k nan
'MINAC11_', #Minutes of Physical Activity per week for First Activity 155k nan
'MINAC21_', #Minutes of Physical Activity per week for Second Activity 157k nan
'STRFREQ_', #Strength Activity Frequency per Week 44k nan
'PAMISS1_', #Missing Physical Activity Data
'PAMIN11_', #Minutes of Physical Activity per week for First Activity 158k nan
'PAMIN21_', #Minutes of Physical Activity per week for Second Activity 160k nan
'PA1MIN_', #Minutes of total Physical Activity per week 152k nan
'PAVIG11_', #Minutes of Vigorous Physical Activity per week for First Activity 153k nan
'PAVIG21_', #Minutes of Vigorous Physical Activity per week for Second Activity 158k nan
'PA1VIGM_', #Minutes of total Vigorous Physical Activity per week 150k nan
'PACAT1_', #Physical Activity Categories
'PAINDX1_', #Physical Activity Index
'PA150R2_', #Adults that participated in 150 minutes (or vigorous equivalent minutes) of physical activity per week.
'PA300R2_', #Adults that participated in 300 minutes (or vigorous equivalent minutes) of physical activity per week.
'PA30021_', #Adults that participated in 300 minutes (or vigorous equivalent minutes) of physical activity per week (2-levels).
'PASTRNG_', #Muscle Strengthening Recommendation
'PAREC1_', #Aerobic and Strengthening Guideline
'PASTAE1_', #Aerobic and Strengthening (2-level)
'LMTACT1_', #Limited usual activities 3k nan
'LMTWRK1_', #Limited work activities 3k nan
'LMTSCL1_', #Limited social activities 3k nan
'RFSEAT2_', #Always or Nearly Always Wear Seat Belts Calculated Variable
'RFSEAT3_', #Always Wear Seat Belts Calculated Variable
'FLSHOT6_', #Adults aged 65+ who have had a flu shot within the past year, 283k nan
'PNEUMO2_', #Adults aged 65+ who have ever had a pneumonia vaccination 283k nan
'AIDTST3_' #Adults who have ever been tested for HIV 43k nan
]
col_indices = get_column_index_from_list(col_list, x_col_name)
print(col_indices)
#load x_train with only the columns in col_indices
x_train_subset = load_data_column('../data/dataset/x_train.csv', column_list=col_indices)
print(x_train_subset)
#expand the colomns in x train_subset
expanded_cols = []
expanded_col_names = []
for i, col_name in enumerate(col_list):
    expanded_col, col_names = expand_column(x_train_subset[:, i], col_name)
    expanded_cols.append(expanded_col)
    expanded_col_names.extend(col_names)
x_train_expanded = np.hstack(expanded_cols)
#add the columns name back to x_train_expanded
print(expanded_col_names)
print(x_train_expanded)
x_train_expanded_dataset = np.vstack((expanded_col_names, x_train_expanded))
#save x_train_expanded to csv
np.savetxt("x_train_expanded.csv", x_train_expanded_dataset, fmt="%s", delimiter=",")
print("x_train_expanded saved to x_train_expanded.csv")


[231, 232, 233, 234, 235, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 262, 263, 267, 268, 269, 270, 271, 272, 273, 274, 275, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 298, 299, 300, 301, 302, 303, 304, 305]
[[ 1.  1.  1. ...  0.  0.  0.]
 [ 2.  1.  2. ...  0.  0.  0.]
 [ 1.  9.  1. ...  0.  0.  0.]
 ...
 [ 1.  9.  1. ...  0.  0.  0.]
 [ 1.  1.  1. ... 14.  0. 14.]
 [ 1.  1.  2. ...  0.  0.  0.]]
Unique values in column '_RFHLTH': [1. 2. 9.]
Unique values in column '_HCVU651': [1. 2. 9.]
Unique values in column '_RFHYPE5': [1. 2. 9.]
Unique values in column '_CHOLCHK': [1. 2. 3. 9.]
Unique values in column '_RFCHOL': [0. 1. 2. 9.]
Unique values in column '_MICHD': [1. 2. 3. 9.]
Unique values in column '_ASTHMS1': [0. 1. 2.]
Unique values in column '_DRDXAR1': [ 1.  2.  3.  4.  5.  6.  7.  8. 77. 99.]
Unique values in column '_PRACE1': [ 1.  2.  3.  4.  5.  6.  7. 77. 99.]
Unique values in column '_MRACE1': [1. 2. 9.]
Unique values in column '_

In [47]:
def build_k_indices(y, k_fold, seed):
    """build k indices for k-fold.

    Args:
        y:      shape=(N,)
        k_fold: K in K-fold, i.e. the fold num
        seed:   the random seed

    Returns:
        A 2D array of shape=(k_fold, N/k_fold) that indicates the data indices for each fold

    >>> build_k_indices(np.array([1., 2., 3., 4.]), 2, 1)
    array([[3, 2],
           [0, 1]])
    """
    num_row = y.shape[0]
    interval = int(num_row / k_fold)
    np.random.seed(seed)
    indices = np.random.permutation(num_row)
    k_indices = [indices[k * interval : (k + 1) * interval] for k in range(k_fold)]
    return np.array(object=k_indices, dtype=int)

In [49]:
#load x_train and y_train
x_train = load_data_column('x_train_expanded.csv', column_list=None)
y_train = load_data_column('../data/dataset/y_train.csv', column_list=None)

In [50]:
#split the dataset in 10 folds and define x_train as 9 out of 10 folds and x_test as the remaining fold, same for y_train and y_test
k_fold = 10
seed = 1
k_indices = build_k_indices(y_train, k_fold, seed)
print(k_indices)
for k in range(k_fold):
    x_test = x_train[k_indices[k]]
    y_test = y_train[k_indices[k]]
    x_train_fold = np.delete(x_train, k_indices[k], axis=0)
    y_train_fold = np.delete(y_train, k_indices[k], axis=0)
    print(f"Fold {k+1}")
    print(f"x_test shape: {x_test.shape}, y_test shape: {y_test.shape}")
    print(f"x_train shape: {x_train_fold.shape}, y_train shape: {y_train_fold.shape}")
#print shape of x_train and y_train and x_test and y_test
print(f"x_train shape: {x_train.shape}, y_train shape: {y_train.shape}")
print(f"x_test shape: {x_test.shape}, y_test shape: {y_test.shape}")

[[  5034 271803 120350 ... 235713 288612  41205]
 [115126 279242  14551 ...  91185 220011 312741]
 [162468 179536  84131 ... 234610 232051 217560]
 ...
 [146820 310758  72754 ... 220201  86341  37943]
 [ 37130 253130  23474 ... 325326  53369 222516]
 [268584 140632 188469 ... 293372 229520  21440]]
Fold 1
x_test shape: (32813, 10), y_test shape: (32813, 2)
x_train shape: (295322, 10), y_train shape: (295322, 2)
Fold 2
x_test shape: (32813, 10), y_test shape: (32813, 2)
x_train shape: (295322, 10), y_train shape: (295322, 2)
Fold 3
x_test shape: (32813, 10), y_test shape: (32813, 2)
x_train shape: (295322, 10), y_train shape: (295322, 2)
Fold 4
x_test shape: (32813, 10), y_test shape: (32813, 2)
x_train shape: (295322, 10), y_train shape: (295322, 2)
Fold 5
x_test shape: (32813, 10), y_test shape: (32813, 2)
x_train shape: (295322, 10), y_train shape: (295322, 2)
Fold 6
x_test shape: (32813, 10), y_test shape: (32813, 2)
x_train shape: (295322, 10), y_train shape: (295322, 2)
Fold 7
x_t

In [51]:
def calculate_loss(y, tx, w):
    """compute the cost by negative log likelihood.

    Args:
        y:  shape=(N, 1)
        tx: shape=(N, D)
        w:  shape=(D, 1)

    Returns:
        a non-negative loss (scalar)
    """

    # compute the loss: negative log likelihood
    y_hat = sigmoid(tx @ w)
    loss = -np.mean(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))
    return float(loss)


def logistic_regression(y, tx, initial_w, max_iters, gamma):
    """Logistic regression using gradient descent.

    Args:
        y: numpy array of shape (N, 1)
        tx: numpy array of shape (N, D)
        initial_w: numpy array of shape (D, 1)
        max_iters: scalar
        gamma: scalar

    Returns:
        losses: list of loss values
        ws: list of weights
    """
    ws = [initial_w]
    w = initial_w
    losses = [calculate_loss(y, tx, w)]
    for n_iter in range(max_iters):
        gradient = calculate_gradient(y, tx, w)
        w = w - gamma * gradient
        loss = calculate_loss(y, tx, w)
        ws.append(w)
        losses.append(loss)

    return ws[-1], np.asarray(losses[-1])


def sigmoid(t):
    """apply sigmoid function on t.

    Args:
        t: scalar or numpy array

    Returns:
        scalar or numpy array
    """

    return 1 / (1 + np.exp(-t))


def calculate_gradient(y, tx, w):
    """compute the gradient of loss.

    Args:
        y:  shape=(N, 1)
        tx: shape=(N, D)
        w:  shape=(D, 1)

    Returns:
        a vector of shape (D, 1)
    """

    y_hat = sigmoid(tx @ w)
    gradient = tx.T @ (y_hat - y) / y.shape[0]
    return gradient


def penalized_logistic_regression(y, tx, w, lambda_):
    """return the loss and gradient.

    Args:
        y:  shape=(N, 1)
        tx: shape=(N, D)
        w:  shape=(D, 1)
        lambda_: scalar

    Returns:
        loss: scalar number
        gradient: shape=(D, 1)
    """
    gradient = calculate_gradient(y, tx, w) + lambda_ * 2 * w
    loss = calculate_loss(y, tx, w)

    return float(loss), gradient

In [53]:
#run penalized logistic regression on x_train and y_train
initial_w = np.zeros((x_train.shape[1], 1))
max_iters = 100
gamma = 0.01
lambda_ = 0.1
loss,w = penalized_logistic_regression(y_train, x_train, initial_w, lambda_)
print(f"Final loss: {loss}")
#cross validate with x-test and y-test
y_pred = sigmoid(x_test @ w) >= 0.5
print(f"Predictions: {y_pred.flatten()}")
print(f"True labels: {y_test.flatten()}")
#compute accuracy
accuracy = np.mean(y_pred.flatten() == y_test.flatten())
print(f"Accuracy: {accuracy * 100:.2f}%")


Final loss: 0.6931471805599453
Predictions: [False  True False ...  True False  True]
True labels: [ 2.68584e+05 -1.00000e+00  1.40632e+05 ... -1.00000e+00  2.14400e+04
 -1.00000e+00]
Accuracy: 4.28%


C:\Users\Utente\AppData\Local\Temp\ipykernel_15976\1154358659.py:56: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-t))
